services:

    wss_db:
        image: postgres:16.3
        container_name: wss_db
        environment:
            POSTGRES_DB: wss_prod
            POSTGRES_USER: wss
            POSTGRES_PASSWORD: WSS
        ports:
            - "5432:5432"
        volumes:
            - wss_db_data:/var/lib/postgresql/data

    wss_db_admin:
        image: dpage/pgadmin4:latest
        container_name: wss_db_admin
        environment:
            PGADMIN_DEFAULT_EMAIL: wss@wss.com
            PGADMIN_DEFAULT_PASSWORD: 'WSS'
        ports:
            - "8080:80"
        volumes:
            - wss_db_admin_data:/var/lib/pgadmin

    wss_server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: wss_server
        ports:
            - "5000:8080"
        environment:
            - Database__Host=wss_db
            - Database__Port=5432
            - Database__Name=wss_prod
            - Database__User=wss
            - Database__Pass=WSS
        depends_on:
            - wss_db

volumes:
    wss_db_data:
    wss_db_admin_data:
